### ISSUE TITLE
incorrect no-file-found response

### ISSUE THREAD

**Issue by ehwest** [vk-twiconnect/twiconnect-client#15]
Having a "sev 1" bug, relating to the situation where the json request by the server is for a file that is not present an/or the folder is not present on the client machine.  

 ```
  at TWIConnect.Client.Processor.Run()
**---> (Inner Exception #0) System.IO.FileNotFoundException: Could not find file 'c:\Aloha\Bootdrv\20181014\ODR.DBF'.**
**File name: 'c:\Aloha\Bootdrv\20181014\ODR.DBF'**
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at TWIConnect.Client.Utilities.FileSystem.LoadFile(FileConfiguration configuration)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

  When the server requests a particular file that happens to be **not** present on the client, updates to Configuration.json parameters fail to stick.

Server sent this json:

{
"LocationKey":"dickeys013",
"ThreadTimeToLiveSec":"5",
"ObjectType":"File",
"Uri":"https:\/\/transactionalweb.com\/ienterprise\/polling\/pollrequest.htm?ver=1539444126",
"ScheduledIntervalSec":5,
"ImmutabilityIntervalSec":10,
"FileSizeLimitMb":"501",
"IgnoreSizeLimit":"False",
"IgnoreImmutabilityInterval":"False",
"SendVersionAfterTimeStampUtc":"1970-01-01T01:01:40",
"Path":"c:\\Aloha\\Bootdrv\\20181013\\ODR.DBF",
"SequenceId":1539444126
}
=============================================================

Server next Received json from client:
{
  "LocationKey": "dickeys013",
  "ScheduledIntervalSec": 29,
  "ThreadTimeToLiveSec": 30,
  "SequenceId": null,
  "Uri": "https://transactionalweb.com/ienterprise/polling/pollrequest.htm?ver=1539443328",
  "DerivedMachineHash": "a3d61dcd929f262dc652ffce4ef61231"
}

The expected response should include the sequenceID and ScheduledIntervalSec of the sent json.
In addition, there seems to be a long delay in continueing the sequence to send this response.  There is an error message:

1) In spite of the failed find on the file contents, updates to the Configuration.json variables should be made for those variables (e.g. SequenceId, ScheduledIntervalSec that were found in the request.
2) Subject to the ScheduleIntervalSec timing, the interval process should proceed.
The server knows this is a failure based on a match to the SequenceID.

The same behivor should apply to Folder retrieval.

```

**Comment by vkhazin** [comment]
The flow diagram: https://github.com/vk-twiconnect/twiconnect-client/blob/master/readme.md
Indicates that Configuration.json is to be updated in one case only when the server returns configuration-update payload with the response status of 200.

* When server requests for file/folder that does not exist, the client will use the configuration returned by the server with all its parameters to post the file/folder data
* The client will not persist any of the settings returned by the server requesting for file/folder or for a command execution - these configurations are not persistent as per design
* The process will fail to load the file/folder, will record the exception into the log file, drop the content of the configuration received from the server, and will wait for the next scheduled interval to repeat the loop starting with previously saved configuration file
* We have not designed anything to handle the file/folder not-found scenario other than falling into the exception flow, recording the exception into log and exiting the current loop
* The command flow follows the same pattern, should command execution fail, the client would record the exception and exit the loop, no update to a persistent configuration will take place
* File/Folder not-found scenarios could be reduced by starting with folder request first, from the root, and then drilling down to the desired location. But even that cannot guarantee that file/folder the server is about to request for won't disappear under the race condition where another process deletes/renames file/folder

I would not recommend implementing an enhancement to save the configuration settings from a file/folder/command request either.

As it may translate to saving a configuration that faults the client on the next scheduled interval, e.g.:
1. server returns a faulty url
2. client stores the url
3. subsequent requests to the url will fail
4. server never gets a chance to instruct client how to recover

**Comment by ehwest** [comment]
OK, got it.

A key aspect of "file-not-found" is that we are polling for files to be found shortly after they are created by a separate automated point of sale process.   So not finding a specific file requested by the server isn't really an "error."  The file just isn't there yet...this is a key reason we have an Immutability time for getting files.

I agree with your comments, but am struggling to find a solid link between the client's presentation of "no-file-found, and the the specific file that was asked for.  I need to update that information in the server's database, if for no other reason as to avoid getting stuck in a rut, asking for the same file over and over again.      (The server database keeps number of fails).

I was at least hoping that the client would cough up the SequenceID provided to it by the server when it asked for the file to be sent, but that is not working.  That would be a great solution, if just that were fixed.   No need to persist it, just give it back to the server.  If we can't do that, then this thing, then I'll have to track state of the client, which isn't ideal.

**Comment by vkhazin** [comment]
How about posting a response back to the server with a message/code and an empty File/Folder content instead?

That to inform server about not-found situation and to give server a chance to respond back with a new config including sequence id?

**Comment by ehwest** [comment]
Yes, some kind of error code would be terrific.
An ErrorMessage would be great "File Not Found"   -- keep it short, or even

Or, better, something HTTP-standard-like  ErrorCode="404"  (File Not Found) (in the Json, not the HTTP header).
May I assume the SequenceID would be the same value as the Server-side property returned to the client when asking for the file?   That would be ideal....right now I'm getting null for the SequenceID.

**Comment by vkhazin** [comment]
https://github.com/vk-twiconnect/twiconnect-client/releases/tag/3.0.6
