### ISSUE TITLE
File delivery: one at a time, no wild-cards

### ISSUE THREAD

**Issue by vkhazin** [vk-twiconnect/twiconnect-client#3]
In Configuration.xml there is a section outlining what files to upload to the server.
There is a support for wildcards and for multiple files.
```
<Files>
    <file>	
      <name><![CDATA[YzpcVEVTVERBVEFcXDIwMTQwNDEzXGM6VEVTVERBVEFcMjAxNDA0MTM=]]></name>	
      <IgnoreSizeLimit>false</IgnoreSizeLimit>	
      <IgnoreImmutabilityInterval>false</IgnoreImmutabilityInterval>	
      <SendVersionAfterTimeStampUtc>1970-01-01T01:01:40</SendVersionAfterTimeStampUtc>	
    </file>
<Files>
```
The requested enhancement is to allow one file upload at a time and ignore wildcard characters.
The xml structure remains the same or <Files> element should be replaced with a single <file> element?

**Comment by vkhazin** [comment]
In Configuration.xml there is a section outlining what files to upload to the server.
There is a support for wildcards and for multiple files.
    <file>	
      <name><![CDATA[YzpcVEVTVERBVEFcXDIwMTQwNDEzXGM6VEVTVERBVEFcMjAxNDA0MTM=]]></name>	
      <IgnoreSizeLimit>false</IgnoreSizeLimit>	
      <IgnoreImmutabilityInterval>false</IgnoreImmutabilityInterval>	
      <SendVersionAfterTimeStampUtc>1970-01-01T01:01:40</SendVersionAfterTimeStampUtc>	
    </file>

The requested enhancement is to allow one file upload at a time and ignore wildcard characters.
The xml structure remains the same or <Files> element should be replaced with a single <file> element?

**Comment by ehwest** [comment]
Here is a sample Configuration.xml file.
This file is ALSO delivered as a payload in the response to authentic POLL queries.
Upon receiving this file in a payload, it should be saved on the local file system,
and then used to govern ongoing polling activity.

 <Configuration>
  <DerivedMachineHash>a3d61dcd929f262dc652ffce4ef61231</DerivedMachineHash>
  <LocationKey>New Site Install</LocationKey>
  <ScheduledIntervalSec>15</ScheduledIntervalSec>
  <FileSizeLimitMb>501</FileSizeLimitMb>
  <ImmutabilityIntervalSec>2</ImmutabilityIntervalSec>
  <MaxThreads>3</MaxThreads>
  <ThreadTimeToLiveSec>15</ThreadTimeToLiveSec>
  <SequenceId>115327179</SequenceId>
  <Files />
  <UrlPostFile><![CDATA[aHR0cDovL3RyYW5zYWN0aW9uYWx3ZWIuY29tL2llbnRlcnByaXNlL3BvbGxyZXF1ZXN0Lmh0bQ==]]></UrlPostFile>
</Configuration>

**Comment by vkhazin** [comment]
Put on hold
